openapi: 3.0.3
info:
  title: Restbucks
  description: OpenAPI definition for the Restbucks imaginary coffee shop
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: "/"
paths: {}
